### PR TITLE
added bootstrap to angular project and created a component that conta…

### PR DESCRIPTION
**Pull request by ekhalsey**
…ins symptom management form

### CODE REVIEW

**Review by jennyjryoo — APPROVED** [review]
Looks good!

**Comment by ekhalsey** [comment]
This branch now has multiple commits. Looks like all will be incorporated in this pull request which is good. 
when you ng serve the form I created should show up at http://localhost:4200/symptomManageForm
I also made a test component just to make sure my routing worked for multiple routes. http://localhost:4200/test

**Review by jennyjryoo — APPROVED** [review]
Looks great!

**Comment by emilykhart** [comment]
Looks good to me! Thanks for getting that setup Emma!

**Review by emilykhart — APPROVED** [review]
Approved!

**Pull request merged**
